import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import { useRouter } from "next/dist/client/router";
import TextField from "@mui/material/TextField";
import Image from "next/image";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Button from "@mui/material/Button";

import useWindowDimensions from "../hooks/useWindowDimensions";
import { scanNEPdfs } from "../api/prod";
import styles from "../styles/Home.module.css";

const theme = createTheme({
  palette: {
    mode: "dark",
  },
});

const Home = () => {
  const { width, height } = useWindowDimensions();
  const router = useRouter();

  const [pendingLetters, setPendingLetters] = useState([]);
  const [approvedLetters, setApprovedLetters] = useState([]);
  const [rejectedLetters, setRejectedLetters] = useState([]);

  const getAllPDFsFunc = async () => {
    const res = await scanNEPdfs();
    const temp_pdfs = JSON.parse(res["body"])["Items"];
    setPendingLetters(
      temp_pdfs.filter((t) => t["approval"]["S"] === "pending")
    );
    setApprovedLetters(
      temp_pdfs.filter((t) => t["approval"]["S"] === "approved")
    );
    setRejectedLetters(
      temp_pdfs.filter((t) => t["approval"]["S"] === "rejected")
    );
  };

  useEffect(() => {
    getAllPDFsFunc();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>TVS Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <div className={styles.logo}>
            <Image
              src="/tvs_logo.png" // Route of the image file
              height={80} // Desired size with correct aspect ratio
              width={200} // Desired size with correct aspect ratio
              alt="TVS Logo"
            />
          </div>

          <div className={styles.empInfo}>
            <div className={styles.empIcon}>R</div>
            <div className={styles.empDropdownContent}>
              <div
                className={styles.empDDList}
                onClick={() => {
                  localStorage.clear();
                  router.push("/");
                }}
              >
                Log Out
              </div>
            </div>
          </div>

          <div className={styles.empCont}>
            <div className={styles.empTitle}>Pending Letters</div>
            <div className={styles.listOfCards}>
              <div className={styles.listOCOuter}>
                {pendingLetters.length > 0 ? (
                  <div className={styles.listOCInner}>
                    {pendingLetters.map((td, i) => (
                      <div
                        key={i}
                        className={styles.createNewCard}
                        style={{ backgroundColor: "#f9aa33" }}
                        onClick={() =>
                          router.push({
                            pathname: "/nepdf",
                            query: {
                              pdfID: td["id"]["S"],
                              approval: td["approval"]["S"],
                            },
                          })
                        }
                      >
                        <div className={styles.cardTitle}>
                          {td["fileName"]["S"]}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className={styles.noData}>Empty List!</div>
                )}
              </div>
            </div>
          </div>

          <div className={styles.empCont}>
            <div className={styles.empTitle}>Approved Letters</div>
            <div className={styles.listOfCards}>
              <div className={styles.listOCOuter}>
                {approvedLetters.length > 0 ? (
                  <div className={styles.listOCInner}>
                    {approvedLetters.map((td, i) => (
                      <div
                        key={i}
                        className={styles.createNewCard}
                        style={{ backgroundColor: "#03DAC5" }}
                        onClick={() =>
                          router.push({
                            pathname: "/nepdf",
                            query: {
                              pdfID: td["id"]["S"],
                              approval: td["approval"]["S"],
                            },
                          })
                        }
                      >
                        <div className={styles.cardTitle}>
                          {td["fileName"]["S"]}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className={styles.noData}>Empty List!</div>
                )}
              </div>
            </div>
          </div>

          <div className={styles.empCont}>
            <div className={styles.empTitle}>Rejected Letters</div>
            <div className={styles.listOfCards}>
              <div className={styles.listOCOuter}>
                {rejectedLetters.length > 0 ? (
                  <div className={styles.listOCInner}>
                    {rejectedLetters.map((td, i) => (
                      <div
                        key={i}
                        className={styles.createNewCard}
                        style={{ backgroundColor: "#e30425" }}
                        onClick={() =>
                          router.push({
                            pathname: "/nepdf",
                            query: {
                              pdfID: td["id"]["S"],
                              approval: td["approval"]["S"],
                            },
                          })
                        }
                      >
                        <div
                          className={styles.cardTitle}
                          style={{ color: "white" }}
                        >
                          {td["fileName"]["S"]}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className={styles.noData}>Empty List!</div>
                )}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
