import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import TextField from "@mui/material/TextField";
import Image from "next/image";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import jwtDecode from "jwt-decode";
import Button from "@mui/material/Button";
import { useRouter } from "next/dist/client/router";

import useWindowDimensions from "../hooks/useWindowDimensions";
import { getToken } from "../api/auth";
import styles from "../styles/Home.module.css";

const theme = createTheme({
  palette: {
    mode: "dark",
  },
});

const Home = () => {
  const { width, height } = useWindowDimensions();
  const router = useRouter();

  const [tab, setTab] = useState("emp");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const getTokenFunc = async () => {
    const res = await getToken(tab, username, password);
    if (res && res.statusCode === 401) return alert("Invalid Credentials!");
    const decodedToken = jwtDecode(res.body);
    if (decodedToken["role"] === "employee") {
      localStorage.setItem("emp-token", res.body);
      router.push("/employee");
    }
    if (decodedToken["role"] === "admin") {
      localStorage.setItem("admin-token", res.body);
      router.push("/admin");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>TVS Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <div className={styles.logo}>
            <Image
              src="/tvs_logo.png" // Route of the image file
              height={80} // Desired size with correct aspect ratio
              width={200} // Desired size with correct aspect ratio
              alt="TVS Logo"
            />
          </div>

          <div className={styles.homeCont}>
            <Image
              src="/icons/signup.svg" // Route of the image file
              height={300} // Desired size with correct aspect ratio
              width={300} // Desired size with correct aspect ratio
              alt="Letter"
            />
            <div>
              <div className={styles.formTabs}>
                <div
                  className={
                    tab === "emp" ? styles.selectedTab : styles.unSelectedTab
                  }
                  onClick={() => setTab("emp")}
                >
                  Employee
                </div>
                <div
                  className={
                    tab === "admin" ? styles.selectedTab : styles.unSelectedTab
                  }
                  onClick={() => setTab("admin")}
                >
                  Admin
                </div>
              </div>

              <div className={styles.formCont}>
                <div className={styles.textField}>
                  <TextField
                    label="Username"
                    variant="outlined"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    style={{ width: 250 }}
                  />
                </div>
                <div className={styles.textField}>
                  <TextField
                    label="Password"
                    variant="outlined"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    style={{ width: 250 }}
                  />
                </div>
              </div>

              <Button
                disabled={username && password ? false : true}
                variant="contained"
                onClick={getTokenFunc}
              >
                Submit
              </Button>
            </div>
          </div>
        </ThemeProvider>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
